### ISSUE TITLE
luna.el: Problems with emacs nativecomp branch

### ISSUE THREAD

**Issue by jeeger** [wanderlust/flim#14]
I've been using the emacs nativecomp branch, and most everything works well. Luna, however, seems to have a problem when used with nativecomp. The error is that ```luna-next-method``` and ```luna-current-method-arguments``` are not defined when loaded from the byte-compiled file. When the file is eval'd, everything works. 

I *believe* that this is due to changes in the compilation, and possibly lexical binding. I've fixed the error by moving the stanza
```emacs-lisp
 (eval-when-compile
  (defvar luna-next-methods nil)
  (defvar luna-current-method-arguments nil))
```
above the function ```luna-send```, which seems to have fixed the error. I'm not entirely sure why.

**Comment by ikazuhiro** [comment]
I've committed the fix, thank you.
I think this is lexical-binding related issue.  These variables are used as let-bound in caller functions, so need to be dynamic variables.  They didn't need to be defined in dynamic-binding environment, so the code you quoted was byte-compiler's warning suppressor.
